"""Window and telemetry display configuration for the MuJoCo UUV GUI."""

from __future__ import annotations

from .config_env import env_int, profile_default_update_ms


TELEMETRY_EVENT_LIMIT = 200
UI_UPDATE_PERIOD_MS = env_int("UUV_GUI_UPDATE_MS", profile_default_update_ms(), 10, 500)
RC_FAST_PERIOD_MS = env_int("UUV_GUI_RC_FAST_PERIOD_MS", 5, 5, 100)
MAX_DEPTH_DISPLAY_M = 2.0
WINDOW_GEOMETRY = "1040x680"
WINDOW_MINSIZE = (900, 560)
TELEMETRY_HIDDEN_WIDTH = 560
TELEMETRY_HIDDEN_MINSIZE = (520, 560)
OUTER_PADDING = 6
GROUP_PADDING = 6
INNER_PADDING = 4
JOYSTICK_CANVAS_SIZE = 130
ATTITUDE_CANVAS_WIDTH = 360
ATTITUDE_CANVAS_HEIGHT = 190
DEPTH_CANVAS_WIDTH = 190
DEPTH_CANVAS_HEIGHT = 96


__all__ = [
    "ATTITUDE_CANVAS_HEIGHT",
    "ATTITUDE_CANVAS_WIDTH",
    "DEPTH_CANVAS_HEIGHT",
    "DEPTH_CANVAS_WIDTH",
    "GROUP_PADDING",
    "INNER_PADDING",
    "JOYSTICK_CANVAS_SIZE",
    "MAX_DEPTH_DISPLAY_M",
    "OUTER_PADDING",
    "RC_FAST_PERIOD_MS",
    "TELEMETRY_EVENT_LIMIT",
    "TELEMETRY_HIDDEN_MINSIZE",
    "TELEMETRY_HIDDEN_WIDTH",
    "UI_UPDATE_PERIOD_MS",
    "WINDOW_GEOMETRY",
    "WINDOW_MINSIZE",
]
