"""RC override constants shared by GUI, replay, and SITL bridges."""

from __future__ import annotations


PWM_CENTER = 1500
RC_VALID_MIN_PWM = 800
RC_VALID_MAX_PWM = 2200
RC_OVERRIDE_CHANNEL_COUNT = 18
PRIMARY_RC_CHANNEL_COUNT = 6
NEUTRAL_DEFAULT_CHANNEL_COUNT = 8
RC_RELEASE_VALUE = 0
RC_IGNORE_VALUE = 65535
RC_EXTENSION_NO_CHANGE_VALUE = 65534


__all__ = [
    "PWM_CENTER",
    "RC_VALID_MIN_PWM",
    "RC_VALID_MAX_PWM",
    "RC_OVERRIDE_CHANNEL_COUNT",
    "PRIMARY_RC_CHANNEL_COUNT",
    "NEUTRAL_DEFAULT_CHANNEL_COUNT",
    "RC_RELEASE_VALUE",
    "RC_IGNORE_VALUE",
    "RC_EXTENSION_NO_CHANGE_VALUE",
]
