<?xml version="1.0"?>
<package format="3">
  <name>auv_mavros_dvl_plugin</name>
  <version>0.1.0</version>
  <description>Organization DVL MAVROS plugin for the packaged MAVROS runtime.</description>
  <maintainer email="kuuve@todo.todo">kuuve</maintainer>
  <license>GPL-3.0-or-later</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>mavros</depend>
  <depend>pluginlib</depend>
  <depend>auv_dvl_a50_msg</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>diagnostic_updater</depend>
  <depend>libmavconn</depend>
  <depend>mavros_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
