<?xml version="1.0"?>
<package format="3">
  <name>auv_imx219_camera</name>
  <version>0.1.0</version>
  <description>ROS 2 camera driver for dual IMX219 CSI cameras on NVIDIA Jetson.</description>
  <maintainer email="user@example.com">AUV Team</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>image_transport</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <build_depend>libgstreamer1.0-dev</build_depend>
  <build_depend>libgstreamer-plugins-base1.0-dev</build_depend>
  <exec_depend>compressed_image_transport</exec_depend>
  <exec_depend>gstreamer1.0-plugins-base</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
