"""MAVLink message constants requested from ArduPilot telemetry."""

from __future__ import annotations

DEFAULT_AP_TELEMETRY_MESSAGE_CONSTANTS = (
    "MAVLINK_MSG_ID_ATTITUDE",
    "MAVLINK_MSG_ID_LOCAL_POSITION_NED",
    "MAVLINK_MSG_ID_SCALED_PRESSURE",
    "MAVLINK_MSG_ID_SCALED_PRESSURE2",
    "MAVLINK_MSG_ID_SCALED_PRESSURE3",
    "MAVLINK_MSG_ID_RC_CHANNELS",
    "MAVLINK_MSG_ID_EKF_STATUS_REPORT",
    "MAVLINK_MSG_ID_VFR_HUD",
    "MAVLINK_MSG_ID_RAW_IMU",
    "MAVLINK_MSG_ID_SCALED_IMU",
)


__all__ = ["DEFAULT_AP_TELEMETRY_MESSAGE_CONSTANTS"]
