"""Built-in simulation profile defaults."""

from __future__ import annotations

from typing import Any


PROFILE_ALIASES: dict[str, str] = {
    "legacy": "legacy",
    "custom": "legacy",
    "current": "current",
    "ellipsoid": "current",
}


DEFAULT_SIM_PROFILES: dict[str, dict[str, Any]] = {
    "legacy": {
        "half_height": 0.147,
        "buoyancy_model": "ellipsoid",
        "buoyancy_scale": 0.9997,
        "buoyancy_slope_scale": 1.0,
        "surface_heave_damping": 18.0,
        "heave_damping_scale": 1.0,
        "cob_torque_scale": 0.20,
        "buoyancy_point_blend": 1.0,
        "cob_x_offset": -0.003,
        "cob_z_offset": 0.010,
        "thruster_voltage": 20.0,
        "thruster_force_max": 65.0,
        "linear_drag": 1.10,
        "angular_drag": 0.32,
        "linear_damping_linear": [1.10, 1.32, 1.54],
        "linear_damping_angular": [0.32, 0.36, 0.28],
        "quadratic_damping_linear": [1.40, 2.00, 2.40],
        "quadratic_damping_angular": [0.10, 0.12, 0.08],
        "added_mass_linear": [1.80, 2.30, 3.00],
        "added_mass_angular": [0.10, 0.12, 0.08],
        "current_world": [0.0, 0.0, 0.0],
        "body_components": [
            {
                "name": "center_enclosure",
                "shape": "cylinder",
                "size": [0.220, 0.120, 0.110],
                "mass": 6.0,
                "mass_pos": [-0.005, 0.0, 0.075],
                "buoyancy_pos": [-0.005, 0.0, 0.060],
                "buoyancy_share": 0.20,
            },
            {
                "name": "port_lower_body",
                "shape": "capsule",
                "size": [0.380, 0.090, 0.090],
                "mass": 4.5,
                "mass_pos": [0.0, 0.208, -0.005],
                "buoyancy_pos": [0.0, 0.208, 0.040],
                "buoyancy_share": 0.40,
            },
            {
                "name": "starboard_lower_body",
                "shape": "capsule",
                "size": [0.380, 0.090, 0.090],
                "mass": 4.5,
                "mass_pos": [0.0, -0.208, -0.005],
                "buoyancy_pos": [0.0, -0.208, 0.040],
                "buoyancy_share": 0.40,
            },
        ],
        "buoyancy_points": [
            {"name": "buoy_ver_lf", "pos": [0.149, 0.2346, 0.040], "share": 0.25, "half_height": 0.090},
            {"name": "buoy_ver_lr", "pos": [-0.171, 0.2346, 0.040], "share": 0.25, "half_height": 0.090},
            {"name": "buoy_ver_rf", "pos": [0.149, -0.2344, 0.040], "share": 0.25, "half_height": 0.090},
            {"name": "buoy_ver_rr", "pos": [-0.171, -0.2344, 0.040], "share": 0.25, "half_height": 0.090},
        ],
        "spin_gain": 22.0,
        "yaw_torque_scale": 1.0,
        "validation_timestep": 0.004,
        "validation_iterations": 20,
        "validation_ls_iterations": 8,
        "validation_step_start": 0.5,
        "validation_step_end": 1.4,
        "validation_total_time": 3.2,
        "validation_step_amp_ratio": 0.35,
    },
    "current": {
        "buoyancy_model": "ellipsoid",
        "buoyancy_scale": 1.0,
        "buoyancy_slope_scale": 1.2,
        "cob_torque_scale": 1.05,
        "buoyancy_point_blend": 1.0,
        "hydrostatic_volume_source": "body_components",
        "hydrostatic_restoring": {
            "active": True,
            "roll_stiffness_nm_per_rad": 83.0,
            "pitch_stiffness_nm_per_rad": 220.0,
        },
        "cob_x_offset": 0.0,
        "cob_z_offset": 0.075,
        "thruster_voltage": 20.0,
        "thruster_force_max": 21.0,
        "mujoco_fluidcoef_scale": [0.5, 0.5, 1.0, 0.5, 0.5],
        "mujoco_fluidcoef_immersion_scale": True,
        "mujoco_fluid_geom_size_scales": {
            "fluid_*_lower_body": [1.0, 1.0, 1.0],
            "fluid_center_enclosure": [1.0, 1.0, 1.0],
        },
        "mujoco_fluidcoef_geom_scales": {
            "fluid_*_lower_body": [9.3, 7.56, 1.625, 0.35, 0.07],
            "fluid_center_enclosure": [5.8528, 8.024, 3.9, 0.16, 0.04],
        },
        "current_world": [0.0, 0.0, 0.0],
        "body_inertia_scale_xyz": [0.65, 2.5, 0.9],
        "body_components": [
            {
                "name": "center_enclosure",
                "shape": "cylinder",
                "size": [0.208, 0.113, 0.108],
                "mass": 6.0,
                "mass_pos": [-0.005, 0.0, 0.010],
                "buoyancy_pos": [-0.005, 0.0, 0.060],
                "buoyancy_share": 0.20,
            },
            {
                "name": "port_lower_body",
                "shape": "capsule",
                "size": [0.355, 0.048, 0.061],
                "mass": 4.5,
                "mass_pos": [-0.004, 0.248, -0.082],
                "buoyancy_pos": [-0.004, 0.248, 0.040],
                "buoyancy_share": 0.40,
            },
            {
                "name": "starboard_lower_body",
                "shape": "capsule",
                "size": [0.355, 0.048, 0.061],
                "mass": 4.5,
                "mass_pos": [-0.004, -0.248, -0.082],
                "buoyancy_pos": [-0.004, -0.248, 0.040],
                "buoyancy_share": 0.40,
            },
        ],
        "buoyancy_points": [
            {
                "name": "buoy_ver_lf",
                "pos": [0.214, 0.248, -0.024],
                "share": 0.25,
                "half_height": 0.061,
            },
            {
                "name": "buoy_ver_lr",
                "pos": [-0.294, 0.248, -0.024],
                "share": 0.25,
                "half_height": 0.061,
            },
            {
                "name": "buoy_ver_rf",
                "pos": [0.214, -0.248, -0.024],
                "share": 0.25,
                "half_height": 0.061,
            },
            {
                "name": "buoy_ver_rr",
                "pos": [-0.294, -0.248, -0.024],
                "share": 0.25,
                "half_height": 0.061,
            },
        ],
        "ellipsoid_model": {
            "active": True,
            "semi_axes": [0.160, 0.106, 0.147],
            "use_shape_volume": False,
        },
        "fossen_residual_hydro": {
            "active": True,
            "added_mass": {
                "active": True,
                "x_u": 2.0,
                "y_v": 2.5,
                "z_w": 0.0,
                "k_p": 0.0,
                "m_q": 0.0,
                "n_r": 0.6,
                "y_r_n_v": 0.0,
                "z_q_m_w": 0.0,
            },
            "linear": {
                "y_v": 20.0,
                "y_r": 0.0,
                "z_w": 18.0,
                "z_q": 0.0,
                "m_w": 0.0,
                "m_q": 0.0,
                "n_v": 0.0,
                "n_r": 0.0,
            },
            "quadratic": {
                "y_abs_v_v": 80.0,
                "y_abs_r_r": 0.0,
                "z_abs_w_w": 60.0,
                "z_abs_q_q": 0.0,
                "m_abs_w_w": 0.0,
                "m_abs_q_q": 0.0,
                "n_abs_v_v": -16.0,
                "n_abs_r_r": 2.4,
            },
            "forward_speed_linear": {
                "y_v": 0.0,
                "y_r": 0.0,
                "z_w": 0.0,
                "z_q": 0.0,
                "z_r": 0.0,
                "m_w": 0.0,
                "m_q": 0.0,
                "n_v": -7.0,
                "n_r": 4.5,
            },
        },
        "spin_gain": 22.0,
        "yaw_torque_scale": 1.0,
        "validation_timestep": 0.005,
        "validation_iterations": 20,
        "validation_ls_iterations": 8,
        "validation_step_start": 0.5,
        "validation_step_end": 1.4,
        "validation_total_time": 3.2,
        "validation_step_amp_ratio": 0.30,
    },
}


__all__ = ["PROFILE_ALIASES", "DEFAULT_SIM_PROFILES"]
