// Browser preview pacing must never alter the ROS sensor publication contract.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const script = fs.readFileSync(path.join(__dirname, '../gui/web_static/app.js'), 'utf8');
const start = script.indexOf('function updateStereoView(');
const end = script.indexOf('function setStereoCameraExpanded(', start);
let now = 0;
const requests = [];
const image = {complete: true, removeAttribute() {}, set src(value) { requests.push(value); }};
const view = {classList: {add() {}, remove() {}}};
const state = {stereoSeq: {left: 0}, previewHz: 4, previewLastFrame: {left: -Infinity}};
const document = {hidden: false};
const context = vm.createContext({state, document, performance: {now: () => now},
  $: id => id.endsWith('Image') ? image : view});
vm.runInContext(script.slice(start, end), context);
const frame = seq => context.updateStereoView('left', {seq, available: true});
frame(1);
now = 100; frame(2);
assert.equal(requests.length, 1, '4fps preview must skip intervening 15Hz sensor frames');
now = 250; frame(3);
assert.equal(requests.length, 2);
assert.match(requests[1], /seq=3$/, 'preview must fetch newest frame instead of queuing old frames');
now = 500; image.complete = false; frame(4);
assert.equal(requests.length, 2, 'do not overlap an unfinished image download');
image.complete = true; document.hidden = true; now = 800; frame(5);
assert.equal(requests.length, 2, 'hidden document must not download images');
document.hidden = false; state.previewHz = 0; frame(6);
assert.equal(requests.length, 2, 'pausing preview must not download images');
state.previewHz = 10; frame(7);
assert.equal(requests.length, 3);
console.log('Camera preview: bounded pacing, latest frame, no overlap, pause and hidden-tab checks passed.');
